import type { ProjectId, ThreadId } from "./baseSchemas";

export const BROWSER_ANNOTATION_MAX_ID_LENGTH = 128;
export const BROWSER_ANNOTATION_MAX_DOCUMENT_KEY_LENGTH = 128;
export const BROWSER_ANNOTATION_MAX_URL_LENGTH = 2_048;
export const BROWSER_ANNOTATION_MAX_PAGE_TITLE_LENGTH = 256;
export const BROWSER_ANNOTATION_MAX_SELECTOR_LENGTH = 1_024;
export const BROWSER_ANNOTATION_MAX_TAG_NAME_LENGTH = 64;
export const BROWSER_ANNOTATION_MAX_ROLE_LENGTH = 64;
export const BROWSER_ANNOTATION_MAX_NAME_LENGTH = 256;
export const BROWSER_ANNOTATION_MAX_TEXT_LENGTH = 280;
export const BROWSER_ANNOTATION_MAX_FINGERPRINT_LENGTH = 128;
export const BROWSER_ANNOTATION_MAX_COMMENT_LENGTH = 4_000;
export const BROWSER_ANNOTATION_MAX_MARKERS = 32;

export interface BrowserAnnotationDocument {
  /** Unpredictable identity regenerated by the isolated guest preload for every document. */
  token: string;
  /** Stable one-way identity of the exact live URL, computed by the trusted main process. */
  key: string;
  url: string;
}

export interface BrowserAnnotationSource {
  url: string;
  pageTitle: string;
}

export interface BrowserAnnotation {
  /** Proposed by the guest and validated by the main process before publication. */
  id: string;
  source: BrowserAnnotationSource;
  selector: string;
  tagName: string;
  role: string | null;
  name: string | null;
  text: string | null;
  fingerprint: string;
  comment: string | null;
  capturedAt: string;
}

export interface BrowserAnnotationMarker {
  id: string;
  ordinal: number;
  documentKey: string;
  source: BrowserAnnotationSource;
  selector: string;
  fingerprint: string;
}

/**
 * Resolved Synara colors used by the isolated annotation guest.
 *
 * The guest cannot inherit CSS custom properties from the desktop renderer,
 * so the renderer resolves the active composer theme to bounded, numeric CSS
 * color values before starting a session.
 */
export interface BrowserAnnotationTheme {
  mode: "light" | "dark";
  accent: string;
  surface: string;
  text: string;
  mutedText: string;
  border: string;
  focusBorder: string;
  primary: string;
  primaryText: string;
}

export interface BrowserAnnotationStartInput {
  threadId: ThreadId;
  tabId: string;
  theme: BrowserAnnotationTheme;
}

export interface BrowserAnnotationCancelInput {
  threadId: ThreadId;
  tabId: string;
}

export interface BrowserAnnotationSyncMarkersInput {
  threadId: ThreadId;
  tabId: string;
  /** Monotonic renderer-owned full-projection version. Stale projections are ignored. */
  version: number;
  markers: readonly BrowserAnnotationMarker[];
}

export interface BrowserAnnotationSession {
  sessionId: string;
  threadId: ThreadId;
  tabId: string;
  document: BrowserAnnotationDocument;
  source: BrowserAnnotationSource;
}

interface BrowserAnnotationEventBase {
  threadId: ThreadId;
  tabId: string;
  document: BrowserAnnotationDocument;
  source: BrowserAnnotationSource;
}

export type BrowserAnnotationCancelReason =
  | "user"
  | "submitted"
  | "navigation"
  | "detached"
  | "destroyed"
  | "replaced";

export type BrowserAnnotationEvent =
  | (BrowserAnnotationEventBase & {
      kind: "started";
      sessionId: string;
    })
  | (BrowserAnnotationEventBase & {
      kind: "cancelled";
      sessionId: string | null;
      reason: BrowserAnnotationCancelReason;
    })
  | (BrowserAnnotationEventBase & {
      kind: "document-changed";
      sessionId: null;
    })
  | (BrowserAnnotationEventBase & {
      kind: "markers-synced";
      sessionId: null;
      version: number;
      projectedMarkerIds: readonly string[];
    })
  | (BrowserAnnotationEventBase & {
      kind: "committed";
      sessionId: string;
      annotation: BrowserAnnotation;
    });

export interface BrowserAnnotationMethods {
  start: (input: BrowserAnnotationStartInput) => Promise<BrowserAnnotationSession>;
  cancel: (input: BrowserAnnotationCancelInput) => Promise<void>;
  syncMarkers: (input: BrowserAnnotationSyncMarkersInput) => Promise<void>;
  onEvent: (listener: (event: BrowserAnnotationEvent) => void) => () => void;
}

// ── Project-owned annotation contracts ─────────────────────────
//
// The Right-sidebar browser/annotation workspace belongs to a Project
// (Decision 0002): annotation sessions, marker projection, and their events
// carry the owning `ProjectId` directly rather than inferring ownership from
// whichever Thread happens to be active. The Thread-keyed interfaces above
// remain the legacy v1 surface until every consumer migrates.

export interface BrowserAnnotationProjectStartInput {
  projectId: ProjectId;
  tabId: string;
  theme: BrowserAnnotationTheme;
}

export interface BrowserAnnotationProjectCancelInput {
  projectId: ProjectId;
  tabId: string;
}

export interface BrowserAnnotationProjectSyncMarkersInput {
  projectId: ProjectId;
  tabId: string;
  /** Monotonic renderer-owned full-projection version. Stale projections are ignored. */
  version: number;
  markers: readonly BrowserAnnotationMarker[];
}

export interface BrowserAnnotationProjectSession {
  sessionId: string;
  projectId: ProjectId;
  tabId: string;
  document: BrowserAnnotationDocument;
  source: BrowserAnnotationSource;
}

interface BrowserAnnotationProjectEventBase {
  projectId: ProjectId;
  tabId: string;
  document: BrowserAnnotationDocument;
  source: BrowserAnnotationSource;
}

export type BrowserAnnotationProjectEvent =
  | (BrowserAnnotationProjectEventBase & {
      kind: "started";
      sessionId: string;
    })
  | (BrowserAnnotationProjectEventBase & {
      kind: "cancelled";
      sessionId: string | null;
      reason: BrowserAnnotationCancelReason;
    })
  | (BrowserAnnotationProjectEventBase & {
      kind: "document-changed";
      sessionId: null;
    })
  | (BrowserAnnotationProjectEventBase & {
      kind: "markers-synced";
      sessionId: null;
      version: number;
      projectedMarkerIds: readonly string[];
    })
  | (BrowserAnnotationProjectEventBase & {
      kind: "committed";
      sessionId: string;
      annotation: BrowserAnnotation;
    });

export interface BrowserAnnotationProjectMethods {
  start: (input: BrowserAnnotationProjectStartInput) => Promise<BrowserAnnotationProjectSession>;
  cancel: (input: BrowserAnnotationProjectCancelInput) => Promise<void>;
  syncMarkers: (input: BrowserAnnotationProjectSyncMarkersInput) => Promise<void>;
  onEvent: (listener: (event: BrowserAnnotationProjectEvent) => void) => () => void;
}
